### PR TITLE
Preview of the Update for the "precompiled" version of Learn-OCaml

### PR DESCRIPTION
**Pull request by AltGr**
(Note: the required version of Learn-OCaml has not been pushed yet)

- easy_check can now be compiled by `dune` by simply depending on `learn-ocaml.test_lib` (and opening `Test_lib.Open_me` for backwards compat). See easy-check/src/dune. Then install it using `dune install`, or, better, through opam once a proper package definition is written.
- in the exercise, `depend.txt` is replaced by `test_libs.txt` that simply lists the libraries to use. `learn-ocaml build` will then automatically find and link the lib into the grader of the exercise.

Additional changes I had to make:
- the lib is compiled with `wrapped true` to avoid a conflict on the `Result` module
- the lib was using an exception `Undefined` expected to be defined in `prepare.ml` — I believe this was a bug and replaced it by a built-in exception so we don't have to make assumptions on `prepare.ml` anymore.

### CODE REVIEW

**Comment by lsylvestre** [comment]
Thank you very much for this PR. 

I will include it once the required version of learn-ocaml is available.

PS:
Actually, the exception `Undefined` is not a bug. 

It serves the same purpose as the exception `TODO` in some exercises of the learn-ocaml corpus:
https://github.com/ocaml-sf/learn-ocaml-corpus/blob/master/exercises/fpottier/merge_sort/prepare.ml#L1

I used it in template.ml to provide default implementations :

```ocaml
let rec fib n = raise Undefined
``` 

But for this update, I fully understand that we can't make any assumptions about prepare.ml

**Comment by AltGr** [comment]
Indeed, I understand the need. Maybe worth providing one such exception already built-in the learn-ocaml toplevel…

**Comment by AltGr** [comment]
Update: I have done just that.

**Comment by lsylvestre** [comment]
Thank you for the new built-in exception
and for the simplifications in the README also.

**Pull request merged**
